# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CET4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField()),
                ('word', models.CharField(max_length=21)),
                ('explanation', models.TextField()),
                ('sentences', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CET6',
            fields=[
                ('word_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20)),
                ('explanation', models.TextField()),
                ('sentences', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_id', models.IntegerField()),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('logo_img', models.CharField(default='http://7xrb5e.com1.z0.glb.clouddn.com/avatar.jpg', max_length=255)),
                ('word_level', models.CharField(default='0', max_length=10)),
                ('daily_word_num', models.IntegerField(null=True)),
                ('user_token', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.User'),
        ),
    ]
